package com.ironhack.labjavajparelationshipsandinheritancesolutions.NurseAssociationDivisionManagement.repository;

import com.ironhack.labjavajparelationshipsandinheritancesolutions.NurseAssociationDivisionManagement.model.Association;
import org.springframework.data.jpa.repository.JpaRepository;

public interface AssociationRepository extends JpaRepository<Association,Long> {

}
